import type { ImplementationConfig } from "./types";

export const DEFAULT_CONFIG: ImplementationConfig = {
  account: {
    organizationName: "",
    departmentName: "",
    country: "India",
    stateProvince: "",
    logoDataUrl: "",
    mobilePrefix: "+91",
    currency: "INR",
    currencySymbol: "₹",
    language: "English",
    dateFormat: "DD/MM/YYYY",
    financialYearStart: "April",
    adminEmail: "",
    adminPhone: "",
    domainSlug: "",
  },
  branding: {
    portalName: "Business License Portal",
    portalTagline: "Apply for your Business License online — fast, simple, and paperless.",
    primaryColor: "#2563eb",
    logoUrl: "",
    copyrightText: "",
  },
  deployment: {
    availabilityScope: "select_cities",
    areas: [{ city: "", zones: [""] }],
    hierarchyName: "",
    hierarchyLevels: [],
    boundaryRows: [],
    uploadMethod: "",
    shapefileName: "",
    operatingLevel: 0,
  },
  overall: {
    renewalEnabled: true,
    renewalReuseIssuanceForm: true,
    renewalApprovalMode: "auto_if_unchanged",
    renewalTriggerDays: 30,
    renewalGracePeriodDays: 15,
    categoryLevels: 2,
    categoryLevelLabels: ["Category", "Sub-Category"],
    categories: [
      { id: "c1",  level1: "Retail Shop",           level2: "Grocery Store",                    level3: "" },
      { id: "c2",  level1: "Retail Shop",           level2: "Clothing & Apparel",               level3: "" },
      { id: "c3",  level1: "Retail Shop",           level2: "Electronics & Mobile",             level3: "" },
      { id: "c4",  level1: "Retail Shop",           level2: "Pharmacy / Chemist",               level3: "" },
      { id: "c5",  level1: "Retail Shop",           level2: "Hardware & Building Materials",    level3: "" },
      { id: "c6",  level1: "Retail Shop",           level2: "Furniture & Home Décor",           level3: "" },
      { id: "c7",  level1: "Food & Beverage",       level2: "Restaurant — Dine-in",             level3: "" },
      { id: "c8",  level1: "Food & Beverage",       level2: "Restaurant — Takeaway / Delivery", level3: "" },
      { id: "c9",  level1: "Food & Beverage",       level2: "Café / Coffee Shop",               level3: "" },
      { id: "c10", level1: "Food & Beverage",       level2: "Bakery & Sweet Shop",              level3: "" },
      { id: "c11", level1: "Food & Beverage",       level2: "Street Food Stall",                level3: "" },
      { id: "c12", level1: "Personal Services",     level2: "Salon & Beauty Parlour",           level3: "" },
      { id: "c13", level1: "Personal Services",     level2: "Laundry & Dry Cleaning",           level3: "" },
      { id: "c14", level1: "Personal Services",     level2: "Tailoring & Alterations",          level3: "" },
      { id: "c15", level1: "Personal Services",     level2: "Gym & Fitness Centre",             level3: "" },
      { id: "c16", level1: "Personal Services",     level2: "Repair Workshop",                  level3: "" },
      { id: "c17", level1: "Healthcare",            level2: "Clinic / Dispensary",              level3: "" },
      { id: "c18", level1: "Healthcare",            level2: "Diagnostic & Pathology Lab",       level3: "" },
      { id: "c19", level1: "Healthcare",            level2: "Optical Store",                    level3: "" },
      { id: "c20", level1: "Professional Services", level2: "IT & Software Services",           level3: "" },
      { id: "c21", level1: "Professional Services", level2: "Accounting & Finance",             level3: "" },
      { id: "c22", level1: "Professional Services", level2: "Consultancy & Advisory",           level3: "" },
      { id: "c23", level1: "Manufacturing",         level2: "Food Processing",                  level3: "" },
      { id: "c24", level1: "Manufacturing",         level2: "Garment & Textile",                level3: "" },
      { id: "c25", level1: "Manufacturing",         level2: "Handicrafts & Artisanal",          level3: "" },
      { id: "c26", level1: "Education & Training",  level2: "Coaching & Tuition Centre",        level3: "" },
      { id: "c27", level1: "Education & Training",  level2: "Vocational Training Institute",    level3: "" },
    ],
    licenseValidityMode: "fixed",
    licenseValidityMonths: 12,
    allowPastYears: false,
    pastYearsAllowed: 1,
    issuanceIdFormat: "BL-YYYY-NNNNNN",
    renewalIdFormat: "RBL-YYYY-NNNNNN",
    licenseIdSameAsApplication: true,
    licenseIdFormat: "LIC-YYYY-NNNNNN",
  },
  integrations: {
    eSignEnabled: false,
    eSignProvider: "",
    digiLockerEnabled: false,
    gstinVerificationEnabled: false,
    aadhaarOtpEnabled: false,
    customIntegrations: [],
    onlinePaymentEnabled: false,
    paymentGatewayPreference: "",
    paymentGatewayDetails: "",
  },
  formConfig: {
    idTypes: ["Aadhaar", "Passport", "Driving License"],
    tradeCategories: [
      { type: "Retail Shop", subcategories: ["Grocery", "Clothing", "Electronics"] },
      { type: "Restaurant", subcategories: ["Dine-in", "Takeaway", "Cloud Kitchen"] },
      { type: "Manufacturing", subcategories: ["Small Scale", "Medium Scale"] },
      { type: "Service Business", subcategories: ["Consultancy", "Repair", "IT Services"] },
    ],
    documents: [
      {
        id: "doc1", name: "Identity Proof",
        formats: ["PDF", "JPG", "PNG"], required: true,
        hasDocTypeDropdown: true,
        docTypes: ["Aadhaar Card", "Passport", "Driving License", "Voter ID", "PAN Card"],
        isRecommended: true,
      },
      {
        id: "doc2", name: "Address Proof",
        formats: ["PDF", "JPG", "PNG"], required: true,
        hasDocTypeDropdown: true,
        docTypes: ["Aadhaar Card", "Voter ID", "Utility Bill", "Bank Statement", "Rent Agreement"],
        isRecommended: true,
      },
      {
        id: "doc3", name: "Business Proof / Trade License",
        formats: ["PDF"], required: true,
        hasDocTypeDropdown: false, docTypes: [],
        isRecommended: true,
      },
      {
        id: "doc4", name: "GST Certificate",
        formats: ["PDF"], required: false,
        hasDocTypeDropdown: false, docTypes: [],
        isRecommended: true,
      },
      {
        id: "doc5", name: "Shop Establishment Certificate",
        formats: ["PDF"], required: false,
        hasDocTypeDropdown: false, docTypes: [],
        isRecommended: true,
      },
      {
        id: "doc6", name: "Property / Lease Agreement",
        formats: ["PDF"], required: false,
        hasDocTypeDropdown: false, docTypes: [],
        isRecommended: true,
      },
    ],
    customSubsections: [],
    customFields: [],
    deletedRecommendedFields: [],
    editedRecommendedFields: {},
    declarationMobileOtpEnabled: false,
  },
  roles: [
    { id: "citizen",           name: "Citizen",            description: "Applicant applying for a Business License",             staffEmails: [], staffMembers: [] },
    { id: "document_verifier", name: "Document Verifier",  description: "Reviews submitted applications and verifies documents",  staffEmails: [], staffMembers: [] },
    { id: "field_inspector",   name: "Field Inspector",    description: "Visits the business site and confirms compliance",       staffEmails: [], staffMembers: [] },
    { id: "approver",          name: "Approver",           description: "Final approving authority for licence issuance",         staffEmails: [], staffMembers: [] },
  ],
  fees: {
    currency: "INR",
    currencySymbol: "₹",
    applicationFee: 500,
    inspectionFeeMode: "slab",
    inspectionFeeFlat: 500,
    inspectionFeeSlabs: [
      { label: "0–100 sq ft",    amount: 500  },
      { label: "100–500 sq ft",  amount: 1000 },
      { label: "500+ sq ft",     amount: 2000 },
    ],
    inspectionSlabDimension: "Business Area (sq ft)",
    hazardSurcharge: 1500,
    licenseFeeMode: "slab",
    licenseFeeFlat: 1000,
    licenseFeeRatePerSqFt: 10,
    licenseFeeSlabs: [
      { label: "0–100 sq ft",    amount: 500  },
      { label: "100–500 sq ft",  amount: 2500 },
      { label: "500+ sq ft",     amount: 5000 },
    ],
    licenseSlabDimension: "Business Area (sq ft)",
    // New fields (Issue #5)
    feeMode: "flat",
    flatFeeAmount: 0,
    customFeeFields: [],
    customFeeSlabs: {},
    customFeeTable: [],
    additionalFeeComponents: [],
    // Renewal fee (Issue #5 extension)
    renewalFeeMode: "flat",
    renewalFlatFeeAmount: 0,
    renewalCustomFeeFields: [],
    renewalCustomFeeSlabs: {},
    renewalCustomFeeTable: [],
    renewalAdditionalFeeComponents: [],
  },
  workflow: {
    approvalLevels: 2,
    processingSlaDays: 7,
    autoEscalate: true,
    escalationAfterDays: 3,
    renewalReminderDays: 30,
    allowCitizenWithdrawal: true,
    stages: [
      {
        id: "submitted",
        name: "Application Submitted",
        actor: "Citizen",
        isStart: true,
        actions: [{ id: "a1", label: "Submit Application", nextStateId: "pending_doc_verification", color: "default" }],
        slaHours: 0,
        notifications: [
          { channel: "email", recipient: "applicant", subject: "Application Submitted" },
          { channel: "sms",   recipient: "applicant", subject: "Application Submitted" },
        ],
        checklistEnabled: false,
      },
      {
        id: "pending_doc_verification",
        name: "Pending Document Verification",
        actor: "Document Verifier",
        actions: [
          { id: "a2", label: "Verify Documents", nextStateId: "pending_inspection",   color: "success" },
          { id: "a3", label: "Send Back",         nextStateId: "pending_resubmission", color: "danger"  },
        ],
        slaHours: 24,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "pending_inspection",
        name: "Pending Inspection",
        actor: "Field Inspector",
        actions: [
          { id: "a4", label: "Complete Inspection", nextStateId: "pending_approval",    color: "success" },
          { id: "a5", label: "Send Back",            nextStateId: "pending_resubmission", color: "danger"  },
        ],
        slaHours: 48,
        notifications: [
          { channel: "email", recipient: "applicant", subject: "Inspection Scheduled" },
          { channel: "sms",   recipient: "applicant", subject: "Inspection Scheduled" },
        ],
        checklistEnabled: true,
      },
      {
        id: "pending_resubmission",
        name: "Pending Resubmission",
        actor: "Citizen",
        actions: [{ id: "a6", label: "Resubmit", nextStateId: "pending_doc_verification", color: "default" }],
        slaHours: 72,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "pending_approval",
        name: "Pending Approval",
        actor: "Approver",
        actions: [
          { id: "a7", label: "Issue License", nextStateId: "pending_payment", color: "success" },
          { id: "a8", label: "Reject",        nextStateId: "rejected",        color: "danger"  },
        ],
        slaHours: 24,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "rejected",
        name: "Rejected",
        actor: "—",
        isEnd: true,
        actions: [],
        slaHours: 0,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "pending_payment",
        name: "Pending Payment",
        actor: "Citizen",
        actions: [{ id: "a9", label: "Pay License Fee", nextStateId: "pending_issuance", color: "success" }],
        slaHours: 72,
        notifications: [
          { channel: "email", recipient: "applicant", subject: "Payment Pending" },
          { channel: "sms",   recipient: "applicant", subject: "Payment Pending" },
        ],
        checklistEnabled: false,
      },
      {
        id: "pending_issuance",
        name: "Pending Issuance",
        actor: "System",
        actions: [{ id: "a10", label: "Issue License", nextStateId: "license_issued", color: "success" }],
        slaHours: 0,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "license_issued",
        name: "License Issued",
        actor: "—",
        isEnd: true,
        actions: [],
        slaHours: 0,
        notifications: [
          { channel: "email", recipient: "applicant", subject: "Your Business License is Ready" },
          { channel: "sms",   recipient: "applicant", subject: "License Ready for Download"     },
        ],
        checklistEnabled: false,
      },
    ],
    checklistItems: [
      { id: "cl1", stageId: "pending_inspection", label: "Site visited",                        fieldType: "checkbox", required: true  },
      { id: "cl2", stageId: "pending_inspection", label: "Business exists at location",         fieldType: "radio",    required: true  },
      { id: "cl3", stageId: "pending_inspection", label: "Compliance verified",                 fieldType: "radio",    required: true  },
      { id: "cl4", stageId: "pending_inspection", label: "Site photos uploaded",                fieldType: "file",     required: true  },
      { id: "cl5", stageId: "pending_inspection", label: "Inspection remarks",                  fieldType: "text",     required: false },
    ],
    renewalStages: [],
    renewalChecklistItems: [],
  },
  notes: "",
  paymentsNotifications: {
    paymentGateway: "razorpay",
    customGatewayName: "",
    counterPaymentsEnabled: false,
    adminEmail: "",
    smsSenderId: "",
    notificationChannels: { email: true, sms: true, push: false, ussd: false },
    notificationTemplates: [
      { id: "n1",  event: "Application Submitted",        channel: "email", recipient: "applicant", subject: "Your application has been submitted successfully. Ref: {APP_ID}" },
      { id: "n2",  event: "Application Submitted",        channel: "sms",   recipient: "applicant", subject: "Application submitted. Ref: {APP_ID}" },
      { id: "n3",  event: "Application Submitted",        channel: "email", recipient: "staff",     subject: "New application received. Ref: {APP_ID} — please review." },
      { id: "n4",  event: "Pending Document Verification",channel: "email", recipient: "applicant", subject: "Your documents are under review. We will notify you once verified." },
      { id: "n5",  event: "Inspection Scheduled",         channel: "email", recipient: "applicant", subject: "A field inspection has been scheduled for your business." },
      { id: "n6",  event: "Inspection Scheduled",         channel: "sms",   recipient: "applicant", subject: "Inspection scheduled. Ref: {APP_ID}" },
      { id: "n7",  event: "Pending Resubmission",         channel: "email", recipient: "applicant", subject: "Action required: please resubmit your application with the requested corrections." },
      { id: "n8",  event: "Pending Resubmission",         channel: "sms",   recipient: "applicant", subject: "Corrections needed. Log in to resubmit. Ref: {APP_ID}" },
      { id: "n9",  event: "Pending Payment",              channel: "email", recipient: "applicant", subject: "Your application is approved — please complete the licence fee payment." },
      { id: "n10", event: "Pending Payment",              channel: "sms",   recipient: "applicant", subject: "Payment pending for licence. Ref: {APP_ID}" },
      { id: "n11", event: "License Issued",               channel: "email", recipient: "applicant", subject: "Congratulations! Your Business Licence has been issued. Ref: {APP_ID}" },
      { id: "n12", event: "License Issued",               channel: "sms",   recipient: "applicant", subject: "Licence issued. Download from the portal. Ref: {APP_ID}" },
    ],
  },
  metadata: {
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "draft",
    lastStep: 1,
  },
};

export const MOBILE_PREFIX_OPTIONS = [
  { prefix: "+91",  country: "India" },
  { prefix: "+234", country: "Nigeria" },
  { prefix: "+254", country: "Kenya" },
  { prefix: "+233", country: "Ghana" },
  { prefix: "+256", country: "Uganda" },
  { prefix: "+255", country: "Tanzania" },
  { prefix: "+27",  country: "South Africa" },
  { prefix: "+251", country: "Ethiopia" },
  { prefix: "+880", country: "Bangladesh" },
  { prefix: "+92",  country: "Pakistan" },
  { prefix: "+44",  country: "United Kingdom" },
  { prefix: "+1",   country: "United States" },
];

export const COUNTRY_TO_PREFIX: Record<string, string> = Object.fromEntries(
  MOBILE_PREFIX_OPTIONS.map((o) => [o.country, o.prefix])
);

export const COLOR_PRESETS = [
  { name: "Government Blue", value: "#2563eb" },
  { name: "Forest Green",    value: "#16a34a" },
  { name: "Deep Indigo",     value: "#4f46e5" },
  { name: "Teal",            value: "#0d9488" },
  { name: "Slate",           value: "#475569" },
];

export const CURRENCY_OPTIONS = [
  { code: "INR", symbol: "₹",   label: "Indian Rupee (₹)"          },
  { code: "NGN", symbol: "₦",   label: "Nigerian Naira (₦)"         },
  { code: "USD", symbol: "$",   label: "US Dollar ($)"              },
  { code: "GBP", symbol: "£",   label: "British Pound (£)"          },
  { code: "KES", symbol: "KSh", label: "Kenyan Shilling (KSh)"      },
  { code: "GHS", symbol: "₵",   label: "Ghanaian Cedi (₵)"          },
];

export const COUNTRY_OPTIONS = [
  "India", "Nigeria", "Kenya", "Ghana", "Uganda", "Tanzania",
  "South Africa", "Ethiopia", "Bangladesh", "Pakistan",
  "United Kingdom", "United States", "Other",
];

export const LANGUAGE_OPTIONS = [
  "English", "Hindi", "Tamil", "Telugu", "Kannada", "Bengali",
  "Yoruba", "Igbo", "Hausa", "Swahili", "French", "Other",
];

export const STORAGE_KEY            = "blp_implementation_config";
export const STEP_KEY               = "blp_current_step";
export const OVERALL_Q_INDEX_KEY    = "blp_overall_q_index";
export const CATEGORIES_CLEARED_KEY = "blp_categories_cleared";
