import type { ImplementationConfig } from "./types";

export const DEFAULT_CONFIG: ImplementationConfig = {
  account: {
    organizationName: "",
    departmentName: "",
    country: "India",
    stateProvince: "",
    logoDataUrl: "",
    mobilePrefix: "+91",
    currency: "INR",
    currencySymbol: "₹",
    language: "English",
    dateFormat: "DD/MM/YYYY",
    financialYearStart: "April",
    adminEmail: "",
    adminPhone: "",
    domainSlug: "",
  },
  branding: {
    portalName: "Business License Portal",
    portalTagline: "Apply for your Business License online — fast, simple, and paperless.",
    primaryColor: "#2563eb",
    logoUrl: "",
    copyrightText: "",
  },
  deployment: {
    availabilityScope: "select_cities",
    areas: [{ city: "", zones: [""] }],
    hierarchyName: "",
    hierarchyLevels: [],
    boundaryRows: [],
    uploadMethod: "",
    shapefileName: "",
    operatingLevel: 0,
  },
  overall: {
    renewalEnabled: true,
    renewalReuseIssuanceForm: true,
    renewalApprovalMode: "auto_if_unchanged",
    renewalTriggerDays: 30,
    renewalGracePeriodDays: 15,
    categoryLevels: 2,
    categoryLevelLabels: ["Category", "Sub-Category"],
    categories: [
      { id: "c1",  level1: "Retail Shop",           level2: "Grocery Store",                    level3: "" },
      { id: "c2",  level1: "Retail Shop",           level2: "Clothing & Apparel",               level3: "" },
      { id: "c3",  level1: "Retail Shop",           level2: "Electronics & Mobile",             level3: "" },
      { id: "c4",  level1: "Retail Shop",           level2: "Pharmacy / Chemist",               level3: "" },
      { id: "c5",  level1: "Retail Shop",           level2: "Hardware & Building Materials",    level3: "" },
      { id: "c6",  level1: "Retail Shop",           level2: "Furniture & Home Décor",           level3: "" },
      { id: "c7",  level1: "Food & Beverage",       level2: "Restaurant — Dine-in",             level3: "" },
      { id: "c8",  level1: "Food & Beverage",       level2: "Restaurant — Takeaway / Delivery", level3: "" },
      { id: "c9",  level1: "Food & Beverage",       level2: "Café / Coffee Shop",               level3: "" },
      { id: "c10", level1: "Food & Beverage",       level2: "Bakery & Sweet Shop",              level3: "" },
      { id: "c11", level1: "Food & Beverage",       level2: "Street Food Stall",                level3: "" },
      { id: "c12", level1: "Personal Services",     level2: "Salon & Beauty Parlour",           level3: "" },
      { id: "c13", level1: "Personal Services",     level2: "Laundry & Dry Cleaning",           level3: "" },
      { id: "c14", level1: "Personal Services",     level2: "Tailoring & Alterations",          level3: "" },
      { id: "c15", level1: "Personal Services",     level2: "Gym & Fitness Centre",             level3: "" },
      { id: "c16", level1: "Personal Services",     level2: "Repair Workshop",                  level3: "" },
      { id: "c17", level1: "Healthcare",            level2: "Clinic / Dispensary",              level3: "" },
      { id: "c18", level1: "Healthcare",            level2: "Diagnostic & Pathology Lab",       level3: "" },
      { id: "c19", level1: "Healthcare",            level2: "Optical Store",                    level3: "" },
      { id: "c20", level1: "Professional Services", level2: "IT & Software Services",           level3: "" },
      { id: "c21", level1: "Professional Services", level2: "Accounting & Finance",             level3: "" },
      { id: "c22", level1: "Professional Services", level2: "Consultancy & Advisory",           level3: "" },
      { id: "c23", level1: "Manufacturing",         level2: "Food Processing",                  level3: "" },
      { id: "c24", level1: "Manufacturing",         level2: "Garment & Textile",                level3: "" },
      { id: "c25", level1: "Manufacturing",         level2: "Handicrafts & Artisanal",          level3: "" },
      { id: "c26", level1: "Education & Training",  level2: "Coaching & Tuition Centre",        level3: "" },
      { id: "c27", level1: "Education & Training",  level2: "Vocational Training Institute",    level3: "" },
    ],
    licenseValidityMode: "fixed",
    licenseValidityMonths: 12,
    allowPastYears: false,
    pastYearsAllowed: 1,
    issuanceIdFormat: "BL-YYYY-NNNNNN",
    renewalIdFormat: "RBL-YYYY-NNNNNN",
    licenseIdSameAsApplication: true,
    licenseIdFormat: "LIC-YYYY-NNNNNN",
  },
  integrations: {
    eSignEnabled: false,
    eSignProvider: "",
    digiLockerEnabled: false,
    gstinVerificationEnabled: false,
    aadhaarOtpEnabled: false,
    customIntegrations: [],
    onlinePaymentEnabled: false,
    paymentGatewayPreference: "",
    paymentGatewayDetails: "",
  },
  formConfig: {
    idTypes: ["Aadhaar", "Passport", "Driving License"],
    tradeCategories: [
      { type: "Retail Shop", subcategories: ["Grocery", "Clothing", "Electronics"] },
      { type: "Restaurant", subcategories: ["Dine-in", "Takeaway", "Cloud Kitchen"] },
      { type: "Manufacturing", subcategories: ["Small Scale", "Medium Scale"] },
      { type: "Service Business", subcategories: ["Consultancy", "Repair", "IT Services"] },
    ],
    documents: [
      {
        id: "doc1", name: "Identity Proof",
        formats: ["PDF", "JPG", "PNG"], required: true,
        hasDocTypeDropdown: true,
        docTypes: ["Aadhaar Card", "Passport", "Driving License", "Voter ID", "PAN Card"],
        isRecommended: true,
      },
      {
        id: "doc2", name: "Address Proof",
        formats: ["PDF", "JPG", "PNG"], required: true,
        hasDocTypeDropdown: true,
        docTypes: ["Aadhaar Card", "Voter ID", "Utility Bill", "Bank Statement", "Rent Agreement"],
        isRecommended: true,
      },
      {
        id: "doc3", name: "Business Proof / Trade License",
        formats: ["PDF"], required: true,
        hasDocTypeDropdown: false, docTypes: [],
        isRecommended: true,
      },
      {
        id: "doc4", name: "GST Certificate",
        formats: ["PDF"], required: false,
        hasDocTypeDropdown: false, docTypes: [],
        isRecommended: true,
      },
      {
        id: "doc5", name: "Shop Establishment Certificate",
        formats: ["PDF"], required: false,
        hasDocTypeDropdown: false, docTypes: [],
        isRecommended: true,
      },
      {
        id: "doc6", name: "Property / Lease Agreement",
        formats: ["PDF"], required: false,
        hasDocTypeDropdown: false, docTypes: [],
        isRecommended: true,
      },
    ],
    customSubsections: [],
    customFields: [],
    deletedRecommendedFields: [],
    editedRecommendedFields: {},
    declarationMobileOtpEnabled: false,
  },
  roles: [
    { id: "citizen",           name: "Citizen",            description: "Applicant applying for a Business License",             staffEmails: [], staffMembers: [] },
    { id: "document_verifier", name: "Document Verifier",  description: "Reviews submitted applications and verifies documents",  staffEmails: [], staffMembers: [] },
    { id: "field_inspector",   name: "Field Inspector",    description: "Visits the business site and confirms compliance",       staffEmails: [], staffMembers: [] },
    { id: "approver",          name: "Approver",           description: "Final approving authority for licence issuance",         staffEmails: [], staffMembers: [] },
  ],
  fees: {
    currency: "INR",
    currencySymbol: "₹",
    applicationFee: 500,
    inspectionFeeMode: "slab",
    inspectionFeeFlat: 500,
    inspectionFeeSlabs: [
      { label: "0–100 sq ft",    amount: 500  },
      { label: "100–500 sq ft",  amount: 1000 },
      { label: "500+ sq ft",     amount: 2000 },
    ],
    inspectionSlabDimension: "Business Area (sq ft)",
    hazardSurcharge: 1500,
    licenseFeeMode: "slab",
    licenseFeeFlat: 1000,
    licenseFeeRatePerSqFt: 10,
    licenseFeeSlabs: [
      { label: "0–100 sq ft",    amount: 500  },
      { label: "100–500 sq ft",  amount: 2500 },
      { label: "500+ sq ft",     amount: 5000 },
    ],
    licenseSlabDimension: "Business Area (sq ft)",
    // New fields (Issue #5)
    feeMode: "flat",
    flatFeeAmount: 0,
    customFeeFields: [],
    customFeeSlabs: {},
    customFeeTable: [],
    additionalFeeComponents: [],
    // Renewal fee (Issue #5 extension)
    renewalFeeMode: "flat",
    renewalFlatFeeAmount: 0,
    renewalCustomFeeFields: [],
    renewalCustomFeeSlabs: {},
    renewalCustomFeeTable: [],
    renewalAdditionalFeeComponents: [],
  },
  workflow: {
    approvalLevels: 2,
    processingSlaDays: 7,
    autoEscalate: true,
    escalationAfterDays: 3,
    renewalReminderDays: 30,
    allowCitizenWithdrawal: true,
    stages: [
      {
        id: "submitted",
        name: "Application Submitted",
        actor: "Citizen",
        isStart: true,
        actions: [{ id: "a1", label: "Submit Application", nextStateId: "pending_doc_verification", color: "default" }],
        slaHours: 0,
        notifications: [
          { channel: "email", recipient: "applicant", subject: "Application Submitted" },
          { channel: "sms",   recipient: "applicant", subject: "Application Submitted" },
        ],
        checklistEnabled: false,
      },
      {
        id: "pending_doc_verification",
        name: "Pending Document Verification",
        actor: "Document Verifier",
        actions: [
          { id: "a2", label: "Verify Documents", nextStateId: "pending_inspection",   color: "success" },
          { id: "a3", label: "Send Back",         nextStateId: "pending_resubmission", color: "danger"  },
        ],
        slaHours: 24,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "pending_inspection",
        name: "Pending Inspection",
        actor: "Field Inspector",
        actions: [
          { id: "a4", label: "Complete Inspection", nextStateId: "pending_approval",    color: "success" },
          { id: "a5", label: "Send Back",            nextStateId: "pending_resubmission", color: "danger"  },
        ],
        slaHours: 48,
        notifications: [
          { channel: "email", recipient: "applicant", subject: "Inspection Scheduled" },
          { channel: "sms",   recipient: "applicant", subject: "Inspection Scheduled" },
        ],
        checklistEnabled: true,
      },
      {
        id: "pending_resubmission",
        name: "Pending Resubmission",
        actor: "Citizen",
        actions: [{ id: "a6", label: "Resubmit", nextStateId: "pending_doc_verification", color: "default" }],
        slaHours: 72,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "pending_approval",
        name: "Pending Approval",
        actor: "Approver",
        actions: [
          { id: "a7", label: "Issue License", nextStateId: "pending_payment", color: "success" },
          { id: "a8", label: "Reject",        nextStateId: "rejected",        color: "danger"  },
        ],
        slaHours: 24,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "rejected",
        name: "Rejected",
        actor: "—",
        isEnd: true,
        actions: [],
        slaHours: 0,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "pending_payment",
        name: "Pending Payment",
        actor: "Citizen",
        actions: [{ id: "a9", label: "Pay License Fee", nextStateId: "pending_issuance", color: "success" }],
        slaHours: 72,
        notifications: [
          { channel: "email", recipient: "applicant", subject: "Payment Pending" },
          { channel: "sms",   recipient: "applicant", subject: "Payment Pending" },
        ],
        checklistEnabled: false,
      },
      {
        id: "pending_issuance",
        name: "Pending Issuance",
        actor: "System",
        actions: [{ id: "a10", label: "Issue License", nextStateId: "license_issued", color: "success" }],
        slaHours: 0,
        notifications: [],
        checklistEnabled: false,
      },
      {
        id: "license_issued",
        name: "License Issued",
        actor: "—",
        isEnd: true,
        actions: [],
        slaHours: 0,
        notifications: [
          { channel: "email", recipient: "applicant", subject: "Your Business License is Ready" },
          { channel: "sms",   recipient: "applicant", subject: "License Ready for Download"     },
        ],
        checklistEnabled: false,
      },
    ],
    checklistItems: [
      { id: "cl1", stageId: "pending_inspection", label: "Site visited",                        fieldType: "checkbox", required: true  },
      { id: "cl2", stageId: "pending_inspection", label: "Business exists at location",         fieldType: "radio",    required: true  },
      { id: "cl3", stageId: "pending_inspection", label: "Compliance verified",                 fieldType: "radio",    required: true  },
      { id: "cl4", stageId: "pending_inspection", label: "Site photos uploaded",                fieldType: "file",     required: true  },
      { id: "cl5", stageId: "pending_inspection", label: "Inspection remarks",                  fieldType: "text",     required: false },
    ],
    checklists: [],
    renewalStages: [],
    renewalChecklistItems: [],
    renewalChecklists: [],
  },
  notes: "",
  paymentsNotifications: {
    paymentGateway: "razorpay",
    customGatewayName: "",
    counterPaymentsEnabled: false,
    adminEmail: "",
    smsSenderId: "",
    notificationChannels: { email: true, sms: true, push: false, ussd: false },
    notificationTemplates: [
      { id: "n1",  event: "Application Submitted",        channel: "email", recipient: "applicant", subject: "Your application has been submitted successfully. Ref: {APP_ID}" },
      { id: "n2",  event: "Application Submitted",        channel: "sms",   recipient: "applicant", subject: "Application submitted. Ref: {APP_ID}" },
      { id: "n3",  event: "Application Submitted",        channel: "email", recipient: "staff",     subject: "New application received. Ref: {APP_ID} — please review." },
      { id: "n4",  event: "Pending Document Verification",channel: "email", recipient: "applicant", subject: "Your documents are under review. We will notify you once verified." },
      { id: "n5",  event: "Inspection Scheduled",         channel: "email", recipient: "applicant", subject: "A field inspection has been scheduled for your business." },
      { id: "n6",  event: "Inspection Scheduled",         channel: "sms",   recipient: "applicant", subject: "Inspection scheduled. Ref: {APP_ID}" },
      { id: "n7",  event: "Pending Resubmission",         channel: "email", recipient: "applicant", subject: "Action required: please resubmit your application with the requested corrections." },
      { id: "n8",  event: "Pending Resubmission",         channel: "sms",   recipient: "applicant", subject: "Corrections needed. Log in to resubmit. Ref: {APP_ID}" },
      { id: "n9",  event: "Pending Payment",              channel: "email", recipient: "applicant", subject: "Your application is approved — please complete the licence fee payment." },
      { id: "n10", event: "Pending Payment",              channel: "sms",   recipient: "applicant", subject: "Payment pending for licence. Ref: {APP_ID}" },
      { id: "n11", event: "License Issued",               channel: "email", recipient: "applicant", subject: "Congratulations! Your Business Licence has been issued. Ref: {APP_ID}" },
      { id: "n12", event: "License Issued",               channel: "sms",   recipient: "applicant", subject: "Licence issued. Download from the portal. Ref: {APP_ID}" },
    ],
  },
  metadata: {
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "draft",
    lastStep: 1,
  },
};

export const MOBILE_PREFIX_OPTIONS = [
  { prefix: "+93",  country: "Afghanistan" },
  { prefix: "+355", country: "Albania" },
  { prefix: "+213", country: "Algeria" },
  { prefix: "+244", country: "Angola" },
  { prefix: "+54",  country: "Argentina" },
  { prefix: "+374", country: "Armenia" },
  { prefix: "+61",  country: "Australia" },
  { prefix: "+43",  country: "Austria" },
  { prefix: "+994", country: "Azerbaijan" },
  { prefix: "+973", country: "Bahrain" },
  { prefix: "+880", country: "Bangladesh" },
  { prefix: "+375", country: "Belarus" },
  { prefix: "+32",  country: "Belgium" },
  { prefix: "+229", country: "Benin" },
  { prefix: "+975", country: "Bhutan" },
  { prefix: "+591", country: "Bolivia" },
  { prefix: "+387", country: "Bosnia and Herzegovina" },
  { prefix: "+267", country: "Botswana" },
  { prefix: "+55",  country: "Brazil" },
  { prefix: "+226", country: "Burkina Faso" },
  { prefix: "+257", country: "Burundi" },
  { prefix: "+855", country: "Cambodia" },
  { prefix: "+237", country: "Cameroon" },
  { prefix: "+1",   country: "Canada" },
  { prefix: "+236", country: "Central African Republic" },
  { prefix: "+235", country: "Chad" },
  { prefix: "+56",  country: "Chile" },
  { prefix: "+86",  country: "China" },
  { prefix: "+57",  country: "Colombia" },
  { prefix: "+242", country: "Congo" },
  { prefix: "+243", country: "DR Congo" },
  { prefix: "+506", country: "Costa Rica" },
  { prefix: "+225", country: "Côte d'Ivoire" },
  { prefix: "+385", country: "Croatia" },
  { prefix: "+53",  country: "Cuba" },
  { prefix: "+357", country: "Cyprus" },
  { prefix: "+420", country: "Czech Republic" },
  { prefix: "+45",  country: "Denmark" },
  { prefix: "+253", country: "Djibouti" },
  { prefix: "+1809",country: "Dominican Republic" },
  { prefix: "+593", country: "Ecuador" },
  { prefix: "+20",  country: "Egypt" },
  { prefix: "+503", country: "El Salvador" },
  { prefix: "+240", country: "Equatorial Guinea" },
  { prefix: "+291", country: "Eritrea" },
  { prefix: "+372", country: "Estonia" },
  { prefix: "+268", country: "Eswatini" },
  { prefix: "+251", country: "Ethiopia" },
  { prefix: "+679", country: "Fiji" },
  { prefix: "+358", country: "Finland" },
  { prefix: "+33",  country: "France" },
  { prefix: "+241", country: "Gabon" },
  { prefix: "+220", country: "Gambia" },
  { prefix: "+995", country: "Georgia" },
  { prefix: "+49",  country: "Germany" },
  { prefix: "+233", country: "Ghana" },
  { prefix: "+30",  country: "Greece" },
  { prefix: "+502", country: "Guatemala" },
  { prefix: "+224", country: "Guinea" },
  { prefix: "+245", country: "Guinea-Bissau" },
  { prefix: "+592", country: "Guyana" },
  { prefix: "+509", country: "Haiti" },
  { prefix: "+504", country: "Honduras" },
  { prefix: "+36",  country: "Hungary" },
  { prefix: "+354", country: "Iceland" },
  { prefix: "+91",  country: "India" },
  { prefix: "+62",  country: "Indonesia" },
  { prefix: "+98",  country: "Iran" },
  { prefix: "+964", country: "Iraq" },
  { prefix: "+353", country: "Ireland" },
  { prefix: "+972", country: "Israel" },
  { prefix: "+39",  country: "Italy" },
  { prefix: "+1876",country: "Jamaica" },
  { prefix: "+81",  country: "Japan" },
  { prefix: "+962", country: "Jordan" },
  { prefix: "+7",   country: "Kazakhstan" },
  { prefix: "+254", country: "Kenya" },
  { prefix: "+383", country: "Kosovo" },
  { prefix: "+965", country: "Kuwait" },
  { prefix: "+996", country: "Kyrgyzstan" },
  { prefix: "+856", country: "Laos" },
  { prefix: "+371", country: "Latvia" },
  { prefix: "+961", country: "Lebanon" },
  { prefix: "+266", country: "Lesotho" },
  { prefix: "+231", country: "Liberia" },
  { prefix: "+218", country: "Libya" },
  { prefix: "+370", country: "Lithuania" },
  { prefix: "+352", country: "Luxembourg" },
  { prefix: "+261", country: "Madagascar" },
  { prefix: "+265", country: "Malawi" },
  { prefix: "+60",  country: "Malaysia" },
  { prefix: "+960", country: "Maldives" },
  { prefix: "+223", country: "Mali" },
  { prefix: "+356", country: "Malta" },
  { prefix: "+222", country: "Mauritania" },
  { prefix: "+230", country: "Mauritius" },
  { prefix: "+52",  country: "Mexico" },
  { prefix: "+373", country: "Moldova" },
  { prefix: "+976", country: "Mongolia" },
  { prefix: "+382", country: "Montenegro" },
  { prefix: "+212", country: "Morocco" },
  { prefix: "+258", country: "Mozambique" },
  { prefix: "+95",  country: "Myanmar" },
  { prefix: "+264", country: "Namibia" },
  { prefix: "+977", country: "Nepal" },
  { prefix: "+31",  country: "Netherlands" },
  { prefix: "+64",  country: "New Zealand" },
  { prefix: "+505", country: "Nicaragua" },
  { prefix: "+227", country: "Niger" },
  { prefix: "+234", country: "Nigeria" },
  { prefix: "+47",  country: "Norway" },
  { prefix: "+968", country: "Oman" },
  { prefix: "+92",  country: "Pakistan" },
  { prefix: "+507", country: "Panama" },
  { prefix: "+675", country: "Papua New Guinea" },
  { prefix: "+595", country: "Paraguay" },
  { prefix: "+51",  country: "Peru" },
  { prefix: "+63",  country: "Philippines" },
  { prefix: "+48",  country: "Poland" },
  { prefix: "+351", country: "Portugal" },
  { prefix: "+974", country: "Qatar" },
  { prefix: "+40",  country: "Romania" },
  { prefix: "+7",   country: "Russia" },
  { prefix: "+250", country: "Rwanda" },
  { prefix: "+966", country: "Saudi Arabia" },
  { prefix: "+221", country: "Senegal" },
  { prefix: "+381", country: "Serbia" },
  { prefix: "+232", country: "Sierra Leone" },
  { prefix: "+65",  country: "Singapore" },
  { prefix: "+421", country: "Slovakia" },
  { prefix: "+386", country: "Slovenia" },
  { prefix: "+252", country: "Somalia" },
  { prefix: "+27",  country: "South Africa" },
  { prefix: "+211", country: "South Sudan" },
  { prefix: "+34",  country: "Spain" },
  { prefix: "+94",  country: "Sri Lanka" },
  { prefix: "+249", country: "Sudan" },
  { prefix: "+597", country: "Suriname" },
  { prefix: "+46",  country: "Sweden" },
  { prefix: "+41",  country: "Switzerland" },
  { prefix: "+963", country: "Syria" },
  { prefix: "+886", country: "Taiwan" },
  { prefix: "+992", country: "Tajikistan" },
  { prefix: "+255", country: "Tanzania" },
  { prefix: "+66",  country: "Thailand" },
  { prefix: "+228", country: "Togo" },
  { prefix: "+1868",country: "Trinidad and Tobago" },
  { prefix: "+216", country: "Tunisia" },
  { prefix: "+90",  country: "Turkey" },
  { prefix: "+993", country: "Turkmenistan" },
  { prefix: "+256", country: "Uganda" },
  { prefix: "+380", country: "Ukraine" },
  { prefix: "+971", country: "United Arab Emirates" },
  { prefix: "+44",  country: "United Kingdom" },
  { prefix: "+1",   country: "United States" },
  { prefix: "+598", country: "Uruguay" },
  { prefix: "+998", country: "Uzbekistan" },
  { prefix: "+58",  country: "Venezuela" },
  { prefix: "+84",  country: "Vietnam" },
  { prefix: "+967", country: "Yemen" },
  { prefix: "+260", country: "Zambia" },
  { prefix: "+263", country: "Zimbabwe" },
];

export const COUNTRY_TO_PREFIX: Record<string, string> = Object.fromEntries(
  MOBILE_PREFIX_OPTIONS.map((o) => [o.country, o.prefix])
);

export const COLOR_PRESETS = [
  { name: "Government Blue", value: "#2563eb" },
  { name: "Forest Green",    value: "#16a34a" },
  { name: "Deep Indigo",     value: "#4f46e5" },
  { name: "Teal",            value: "#0d9488" },
  { name: "Slate",           value: "#475569" },
];

export const CURRENCY_OPTIONS = [
  { code: "AFN", symbol: "؋",   label: "Afghan Afghani (؋)" },
  { code: "ALL", symbol: "L",   label: "Albanian Lek (L)" },
  { code: "DZD", symbol: "د.ج", label: "Algerian Dinar (د.ج)" },
  { code: "AOA", symbol: "Kz",  label: "Angolan Kwanza (Kz)" },
  { code: "ARS", symbol: "$",   label: "Argentine Peso ($)" },
  { code: "AMD", symbol: "֏",   label: "Armenian Dram (֏)" },
  { code: "AUD", symbol: "A$",  label: "Australian Dollar (A$)" },
  { code: "AZN", symbol: "₼",   label: "Azerbaijani Manat (₼)" },
  { code: "BHD", symbol: ".د.ب",label: "Bahraini Dinar (.د.ب)" },
  { code: "BDT", symbol: "৳",   label: "Bangladeshi Taka (৳)" },
  { code: "BYR", symbol: "Br",  label: "Belarusian Ruble (Br)" },
  { code: "BZD", symbol: "BZ$", label: "Belize Dollar (BZ$)" },
  { code: "BOB", symbol: "Bs.", label: "Bolivian Boliviano (Bs.)" },
  { code: "BAM", symbol: "KM",  label: "Bosnia Mark (KM)" },
  { code: "BWP", symbol: "P",   label: "Botswana Pula (P)" },
  { code: "BRL", symbol: "R$",  label: "Brazilian Real (R$)" },
  { code: "BND", symbol: "B$",  label: "Brunei Dollar (B$)" },
  { code: "BGN", symbol: "лв",  label: "Bulgarian Lev (лв)" },
  { code: "BIF", symbol: "Fr",  label: "Burundian Franc (Fr)" },
  { code: "XOF", symbol: "Fr",  label: "CFA Franc BCEAO (Fr)" },
  { code: "XAF", symbol: "Fr",  label: "CFA Franc BEAC (Fr)" },
  { code: "KHR", symbol: "៛",   label: "Cambodian Riel (៛)" },
  { code: "CAD", symbol: "C$",  label: "Canadian Dollar (C$)" },
  { code: "CVE", symbol: "$",   label: "Cape Verdean Escudo ($)" },
  { code: "CLP", symbol: "$",   label: "Chilean Peso ($)" },
  { code: "CNY", symbol: "¥",   label: "Chinese Yuan (¥)" },
  { code: "COP", symbol: "$",   label: "Colombian Peso ($)" },
  { code: "CDF", symbol: "Fr",  label: "Congolese Franc (Fr)" },
  { code: "CRC", symbol: "₡",   label: "Costa Rican Colón (₡)" },
  { code: "HRK", symbol: "kn",  label: "Croatian Kuna (kn)" },
  { code: "CZK", symbol: "Kč",  label: "Czech Koruna (Kč)" },
  { code: "DKK", symbol: "kr",  label: "Danish Krone (kr)" },
  { code: "DJF", symbol: "Fr",  label: "Djiboutian Franc (Fr)" },
  { code: "DOP", symbol: "RD$", label: "Dominican Peso (RD$)" },
  { code: "EGP", symbol: "£",   label: "Egyptian Pound (£)" },
  { code: "ETB", symbol: "Br",  label: "Ethiopian Birr (Br)" },
  { code: "EUR", symbol: "€",   label: "Euro (€)" },
  { code: "FJD", symbol: "FJ$", label: "Fijian Dollar (FJ$)" },
  { code: "GMD", symbol: "D",   label: "Gambian Dalasi (D)" },
  { code: "GEL", symbol: "₾",   label: "Georgian Lari (₾)" },
  { code: "GHS", symbol: "₵",   label: "Ghanaian Cedi (₵)" },
  { code: "GTQ", symbol: "Q",   label: "Guatemalan Quetzal (Q)" },
  { code: "GNF", symbol: "Fr",  label: "Guinean Franc (Fr)" },
  { code: "GYD", symbol: "$",   label: "Guyanese Dollar ($)" },
  { code: "HTG", symbol: "G",   label: "Haitian Gourde (G)" },
  { code: "HNL", symbol: "L",   label: "Honduran Lempira (L)" },
  { code: "HKD", symbol: "HK$", label: "Hong Kong Dollar (HK$)" },
  { code: "HUF", symbol: "Ft",  label: "Hungarian Forint (Ft)" },
  { code: "ISK", symbol: "kr",  label: "Icelandic Króna (kr)" },
  { code: "INR", symbol: "₹",   label: "Indian Rupee (₹)" },
  { code: "IDR", symbol: "Rp",  label: "Indonesian Rupiah (Rp)" },
  { code: "IRR", symbol: "﷼",   label: "Iranian Rial (﷼)" },
  { code: "IQD", symbol: "ع.د", label: "Iraqi Dinar (ع.د)" },
  { code: "ILS", symbol: "₪",   label: "Israeli Shekel (₪)" },
  { code: "JMD", symbol: "J$",  label: "Jamaican Dollar (J$)" },
  { code: "JPY", symbol: "¥",   label: "Japanese Yen (¥)" },
  { code: "JOD", symbol: "د.ا", label: "Jordanian Dinar (د.ا)" },
  { code: "KZT", symbol: "₸",   label: "Kazakhstani Tenge (₸)" },
  { code: "KES", symbol: "KSh", label: "Kenyan Shilling (KSh)" },
  { code: "KWD", symbol: "د.ك", label: "Kuwaiti Dinar (د.ك)" },
  { code: "KGS", symbol: "лв",  label: "Kyrgystani Som (лв)" },
  { code: "LAK", symbol: "₭",   label: "Laotian Kip (₭)" },
  { code: "LBP", symbol: "£",   label: "Lebanese Pound (£)" },
  { code: "LSL", symbol: "L",   label: "Lesotho Loti (L)" },
  { code: "LRD", symbol: "$",   label: "Liberian Dollar ($)" },
  { code: "LYD", symbol: "ل.د", label: "Libyan Dinar (ل.د)" },
  { code: "MGA", symbol: "Ar",  label: "Malagasy Ariary (Ar)" },
  { code: "MWK", symbol: "MK",  label: "Malawian Kwacha (MK)" },
  { code: "MYR", symbol: "RM",  label: "Malaysian Ringgit (RM)" },
  { code: "MVR", symbol: "Rf",  label: "Maldivian Rufiyaa (Rf)" },
  { code: "MRU", symbol: "UM",  label: "Mauritanian Ouguiya (UM)" },
  { code: "MUR", symbol: "Rs",  label: "Mauritian Rupee (Rs)" },
  { code: "MXN", symbol: "$",   label: "Mexican Peso ($)" },
  { code: "MDL", symbol: "L",   label: "Moldovan Leu (L)" },
  { code: "MNT", symbol: "₮",   label: "Mongolian Tögrög (₮)" },
  { code: "MAD", symbol: "د.م.", label: "Moroccan Dirham (د.م.)" },
  { code: "MZN", symbol: "MT",  label: "Mozambican Metical (MT)" },
  { code: "MMK", symbol: "K",   label: "Myanmar Kyat (K)" },
  { code: "NAD", symbol: "$",   label: "Namibian Dollar ($)" },
  { code: "NPR", symbol: "Rs",  label: "Nepalese Rupee (Rs)" },
  { code: "NZD", symbol: "NZ$", label: "New Zealand Dollar (NZ$)" },
  { code: "NIO", symbol: "C$",  label: "Nicaraguan Córdoba (C$)" },
  { code: "NGN", symbol: "₦",   label: "Nigerian Naira (₦)" },
  { code: "NOK", symbol: "kr",  label: "Norwegian Krone (kr)" },
  { code: "OMR", symbol: "﷼",   label: "Omani Rial (﷼)" },
  { code: "PKR", symbol: "Rs",  label: "Pakistani Rupee (Rs)" },
  { code: "PAB", symbol: "B/.", label: "Panamanian Balboa (B/.)" },
  { code: "PGK", symbol: "K",   label: "Papua New Guinean Kina (K)" },
  { code: "PYG", symbol: "₲",   label: "Paraguayan Guaraní (₲)" },
  { code: "PEN", symbol: "S/.", label: "Peruvian Sol (S/.)" },
  { code: "PHP", symbol: "₱",   label: "Philippine Peso (₱)" },
  { code: "PLN", symbol: "zł",  label: "Polish Złoty (zł)" },
  { code: "QAR", symbol: "﷼",   label: "Qatari Riyal (﷼)" },
  { code: "RON", symbol: "lei", label: "Romanian Leu (lei)" },
  { code: "RUB", symbol: "₽",   label: "Russian Ruble (₽)" },
  { code: "RWF", symbol: "Fr",  label: "Rwandan Franc (Fr)" },
  { code: "SAR", symbol: "﷼",   label: "Saudi Riyal (﷼)" },
  { code: "RSD", symbol: "din", label: "Serbian Dinar (din)" },
  { code: "SLL", symbol: "Le",  label: "Sierra Leonean Leone (Le)" },
  { code: "SGD", symbol: "S$",  label: "Singapore Dollar (S$)" },
  { code: "SOS", symbol: "Sh",  label: "Somali Shilling (Sh)" },
  { code: "ZAR", symbol: "R",   label: "South African Rand (R)" },
  { code: "SSP", symbol: "£",   label: "South Sudanese Pound (£)" },
  { code: "LKR", symbol: "Rs",  label: "Sri Lankan Rupee (Rs)" },
  { code: "SDG", symbol: "£",   label: "Sudanese Pound (£)" },
  { code: "SRD", symbol: "$",   label: "Surinamese Dollar ($)" },
  { code: "SEK", symbol: "kr",  label: "Swedish Krona (kr)" },
  { code: "CHF", symbol: "Fr",  label: "Swiss Franc (Fr)" },
  { code: "TWD", symbol: "NT$", label: "Taiwan Dollar (NT$)" },
  { code: "TJS", symbol: "SM",  label: "Tajikistani Somoni (SM)" },
  { code: "TZS", symbol: "Sh",  label: "Tanzanian Shilling (Sh)" },
  { code: "THB", symbol: "฿",   label: "Thai Baht (฿)" },
  { code: "TTD", symbol: "TT$", label: "Trinidad Dollar (TT$)" },
  { code: "TND", symbol: "د.ت", label: "Tunisian Dinar (د.ت)" },
  { code: "TRY", symbol: "₺",   label: "Turkish Lira (₺)" },
  { code: "TMT", symbol: "T",   label: "Turkmenistani Manat (T)" },
  { code: "UGX", symbol: "Sh",  label: "Ugandan Shilling (Sh)" },
  { code: "UAH", symbol: "₴",   label: "Ukrainian Hryvnia (₴)" },
  { code: "AED", symbol: "د.إ", label: "UAE Dirham (د.إ)" },
  { code: "GBP", symbol: "£",   label: "British Pound (£)" },
  { code: "USD", symbol: "$",   label: "US Dollar ($)" },
  { code: "UYU", symbol: "$U",  label: "Uruguayan Peso ($U)" },
  { code: "UZS", symbol: "лв",  label: "Uzbekistani Som (лв)" },
  { code: "VES", symbol: "Bs.S",label: "Venezuelan Bolívar (Bs.S)" },
  { code: "VND", symbol: "₫",   label: "Vietnamese Dong (₫)" },
  { code: "YER", symbol: "﷼",   label: "Yemeni Rial (﷼)" },
  { code: "ZMW", symbol: "ZK",  label: "Zambian Kwacha (ZK)" },
  { code: "ZWL", symbol: "$",   label: "Zimbabwean Dollar ($)" },
];

export const COUNTRY_OPTIONS = [
  "Afghanistan", "Albania", "Algeria", "Angola", "Argentina", "Armenia",
  "Australia", "Austria", "Azerbaijan", "Bahrain", "Bangladesh", "Belarus",
  "Belgium", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana",
  "Brazil", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada",
  "Central African Republic", "Chad", "Chile", "China", "Colombia", "Congo",
  "Costa Rica", "Côte d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic",
  "Denmark", "Djibouti", "Dominican Republic", "DR Congo", "Ecuador", "Egypt",
  "El Salvador", "Equatorial Guinea", "Eritrea", "Eswatini", "Estonia", "Ethiopia",
  "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
  "Greece", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
  "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
  "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kosovo", "Kuwait",
  "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
  "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives",
  "Mali", "Malta", "Mauritania", "Mauritius", "Mexico", "Moldova", "Mongolia",
  "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nepal",
  "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway",
  "Oman", "Pakistan", "Panama", "Papua New Guinea", "Paraguay", "Peru",
  "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda",
  "Saudi Arabia", "Senegal", "Serbia", "Sierra Leone", "Singapore", "Slovakia",
  "Slovenia", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka",
  "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan",
  "Tanzania", "Thailand", "Togo", "Trinidad and Tobago", "Tunisia", "Turkey",
  "Turkmenistan", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
  "United States", "Uruguay", "Uzbekistan", "Venezuela", "Vietnam", "Yemen",
  "Zambia", "Zimbabwe", "Other",
];

export const LANGUAGE_OPTIONS = [
  "English", "Hindi", "Tamil", "Telugu", "Kannada", "Bengali",
  "Yoruba", "Igbo", "Hausa", "Swahili", "French", "Other",
];

export const STORAGE_KEY            = "blp_implementation_config";
export const STEP_KEY               = "blp_current_step";
export const OVERALL_Q_INDEX_KEY    = "blp_overall_q_index";
export const CATEGORIES_CLEARED_KEY = "blp_categories_cleared";
