/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessArnRouteImport } from './routes/success.$arn'
import { Route as PayArnRouteImport } from './routes/pay.$arn'
import { Route as ApplyServiceIdRouteImport } from './routes/apply.$serviceId'
import { Route as ApplicationsArnRouteImport } from './routes/applications.$arn'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessArnRoute = SuccessArnRouteImport.update({
  id: '/success/$arn',
  path: '/success/$arn',
  getParentRoute: () => rootRouteImport,
} as any)
const PayArnRoute = PayArnRouteImport.update({
  id: '/pay/$arn',
  path: '/pay/$arn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyServiceIdRoute = ApplyServiceIdRouteImport.update({
  id: '/apply/$serviceId',
  path: '/apply/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsArnRoute = ApplicationsArnRouteImport.update({
  id: '/applications/$arn',
  path: '/applications/$arn',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/applications': typeof AppApplicationsRoute
  '/documents': typeof AppDocumentsRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/services': typeof AppServicesRoute
  '/applications/$arn': typeof ApplicationsArnRoute
  '/apply/$serviceId': typeof ApplyServiceIdRoute
  '/pay/$arn': typeof PayArnRoute
  '/success/$arn': typeof SuccessArnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/applications': typeof AppApplicationsRoute
  '/documents': typeof AppDocumentsRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/services': typeof AppServicesRoute
  '/applications/$arn': typeof ApplicationsArnRoute
  '/apply/$serviceId': typeof ApplyServiceIdRoute
  '/pay/$arn': typeof PayArnRoute
  '/success/$arn': typeof SuccessArnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/services': typeof AppServicesRoute
  '/applications/$arn': typeof ApplicationsArnRoute
  '/apply/$serviceId': typeof ApplyServiceIdRoute
  '/pay/$arn': typeof PayArnRoute
  '/success/$arn': typeof SuccessArnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/notifications'
    | '/applications'
    | '/documents'
    | '/home'
    | '/profile'
    | '/services'
    | '/applications/$arn'
    | '/apply/$serviceId'
    | '/pay/$arn'
    | '/success/$arn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/notifications'
    | '/applications'
    | '/documents'
    | '/home'
    | '/profile'
    | '/services'
    | '/applications/$arn'
    | '/apply/$serviceId'
    | '/pay/$arn'
    | '/success/$arn'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/notifications'
    | '/_app/applications'
    | '/_app/documents'
    | '/_app/home'
    | '/_app/profile'
    | '/_app/services'
    | '/applications/$arn'
    | '/apply/$serviceId'
    | '/pay/$arn'
    | '/success/$arn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  NotificationsRoute: typeof NotificationsRoute
  ApplicationsArnRoute: typeof ApplicationsArnRoute
  ApplyServiceIdRoute: typeof ApplyServiceIdRoute
  PayArnRoute: typeof PayArnRoute
  SuccessArnRoute: typeof SuccessArnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success/$arn': {
      id: '/success/$arn'
      path: '/success/$arn'
      fullPath: '/success/$arn'
      preLoaderRoute: typeof SuccessArnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$arn': {
      id: '/pay/$arn'
      path: '/pay/$arn'
      fullPath: '/pay/$arn'
      preLoaderRoute: typeof PayArnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$serviceId': {
      id: '/apply/$serviceId'
      path: '/apply/$serviceId'
      fullPath: '/apply/$serviceId'
      preLoaderRoute: typeof ApplyServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$arn': {
      id: '/applications/$arn'
      path: '/applications/$arn'
      fullPath: '/applications/$arn'
      preLoaderRoute: typeof ApplicationsArnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppServicesRoute: typeof AppServicesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRoute,
  AppServicesRoute: AppServicesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  NotificationsRoute: NotificationsRoute,
  ApplicationsArnRoute: ApplicationsArnRoute,
  ApplyServiceIdRoute: ApplyServiceIdRoute,
  PayArnRoute: PayArnRoute,
  SuccessArnRoute: SuccessArnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
